---
title: "mailmerge_email"
author: "Alexander Nielson"
date: "6/22/2021"
output: html_document
---


# Libraries

```{r, message=FALSE}
library(lubridate)
library(data.table)
library(magrittr)
library(stringi)
library(salesforcer)
library(dplyr)
```

```{r}
notice_type  <- 
  #"60_day_notice"
  "hold_or_suspend"

last_report_date <- "2020-11-16"
```


## Connect to Salesforce
```{r}
sf = sf_auth(
  username='alexnielson@utah.gov', 
  password='Muckdweller2020*', 
  security_token='aDpHQzQd4qIVsGxM6fgh3RId')
```


# Functions 

<!-- # ```{r} -->
<!-- # create_file_names <- function(entity_name){ -->
<!-- #   entity_name %>% -->
<!-- #     str_to_lower() %>% -->
<!-- #     str_replace_all("[[:punct:]]","") %>%  -->
<!-- #     str_replace_all(" +","_") %>%  -->
<!-- #     paste0(.,".pdf") -->
<!-- # } -->
<!-- # ``` -->

```{r}
alex_mon_names <<- month.abb %>% stri_trans_toupper()

comma_sep_to_ordered_list <- function(comma_str){
  
  if (is.null(comma_str) || is.na(comma_str)|| comma_str==""||comma_str=="NA"){
    HTML(paste0("NA"))
  }else{
    
    HTML(
      # paste0("<ul>",
      paste0(
        "<li>",
        comma_str %>% stri_split_regex(", ") %>% unlist(),
        "</li>", collapse=""
      )#,
      # "</ul>"
      #)
      
    )
  }
}
```


```{r}
fix_exprev_str_v2 <-  function(exp_str) {
  if (is.null(exp_str) || is.na(exp_str) || exp_str == "") {
    "NA"
  } else{
    exp_str %>%
      stri_split_regex(", ") %>%
      as.data.table() %>%
      .[, `:=`(
        yr = V1 %>% stri_extract_first_regex("^\\d{4}"),
        m1 = V1 %>% stri_extract_first_regex("\\w{3}(?=-)") %>% match(alex_mon_names),
        m2 = V1 %>% stri_extract_first_regex("\\w{3}$") %>% match(alex_mon_names)
      )] %>%
      .[,
        `:=`(m2_lag = lag(m2)), by = c("yr")] %>%
      .[,
        `:=`(has_jump = fifelse(is.na(m2_lag),
                                "no",
                                fifelse(m1 == m2_lag + 1,
                                        "no",
                                        "yes")))] %>%
      .[, `:=`(is_followed_by_jump = lead(has_jump))] %>%
      .[, `:=`(
        min_month = fifelse(has_jump == "yes",
                            m1,
                            min(m1)),
        max_month = fifelse(
          is.na(is_followed_by_jump),
          m2,
          fifelse(is_followed_by_jump == "yes",
                  m2,
                  max(m2))
          
        )
      ), by = c("yr")] %>%
      .[, .(maximin_mon = max(min_month),
            minimax_mon = min(max_month)),
        by = c("yr", "has_jump")] %>%
      .[, `:=`(maximin_mon = alex_mon_names[maximin_mon],
               minimax_mon = alex_mon_names[minimax_mon])] %>%
      .[, `:=`(miss_str = paste0(yr, " ", maximin_mon, "-", minimax_mon))] %>%
      .[, miss_str] %>%
      paste0(collapse = ", ") %>% 
      stri_replace_all_regex(", NA NA-NA", "") 
  }
  
}
```

```{r}
create_email_pdf <-
  function(    miss_exp_p,
              miss_rev_p,
              miss_pay_p,
              miss_lg_p,
              miss_dandi_p,
              entity_name_p,
              file_dir_p,
              file_name_p,
              report_type_p,
              report_types_p=c('transparency', 'auditor', 'treasurer')) {

    # report_type_p = c('mm_email_template_60day_notice.Rmd', 'mm_email_template_10day_notice.Rmd', 'mm_email_template_hold_notice.Rmd','mm_email_template.Rmd' )

    
    #Render the specified email template
    rmarkdown::render(
      report_type_p,
      params = list(
                  miss_exp=miss_exp_p,
              miss_rev=miss_rev_p,
              miss_pay=miss_pay_p,
              miss_lg=miss_lg_p,
              miss_dandi=miss_dandi_p,
              entity_name=entity_name_p,
              report_types = report_types_p
      ),
      output_file = file_name_p,
      output_dir = file_dir_p
      
    )
    
  }


create_email_pdf(    miss_exp_p ="2020 APR-JUN, 2019 JAN-DEC, 2020 APR-JUN, 2019 JAN-DEC",
              miss_rev_p = "2020 APR-JUN",
              miss_pay_p = "2020",
              miss_lg_p="2020 Financial Report",
              miss_dandi_p="2020 D and I June",
              entity_name_p="Test Entity 2",
              file_dir_p="D:/rprojects/compliance-report/mm/email",
              file_name_p="test.pdf",
              report_type_p="mm_email_template_60day_notice.Rmd",
              report_types_p=c('transparency', 'auditor', 'treasurer'))
```


```{r}
create_email_pdf_file_name <- function(entity_name_p){
  entity_name_p %>% 
    stri_trans_tolower() %>%
    stri_replace_all_regex("[[:punct:]]","") %>% 
    stri_replace_all_regex(" +","_") %>% 
    paste0(.,".pdf")
}
```



# III.Contact_info




## query Account object


```{r}
# Get all possible entities and their billing/shipping information.

temp_soql <- paste0(" SELECT 
                        Name,
                        Id,
                        Transparency_ID__c,
                        Entity_Status__c,
                        Is_Solely_Fee_Assessing__c,
                        ShippingStreet,
                        ShippingCity,
                        ShippingState,
                        ShippingPostalCode,
                        BillingStreet,
                        BillingCity,
                        BillingState,
                        BillingPostalCode,
                        Mailing_county__c,
                        Tax_Holding_County__c,
                        FINET_Vendor_Code__c,
                        Fiscal_Year_End_New__c,
                        RecordType.Name
                        
                      FROM Account
                    
                    ")

sf_account <- sf_query(temp_soql)%>%
  as.data.table() %>% 
  .[,.( 
    sf_name           = Name,
    non_taxing_entity = Is_Solely_Fee_Assessing__c,
    sf_id             = Id,
    aws_id            = Transparency_ID__c,
    govt_lvl = RecordType.Name,
    entity_status     = Entity_Status__c,
    ship_street       = ShippingStreet,
    ship_city         = ShippingCity,
    ship_state        = ShippingState,
    ship_pc           = ShippingPostalCode,
    bill_street       = BillingStreet,
    bill_city         = BillingCity,
    bill_state        = BillingState,
    bill_pc           = BillingPostalCode,
    mailing_county    = Mailing_county__c,
    tax_holding_county_id= Tax_Holding_County__c,
    finet_vendor_code = FINET_Vendor_Code__c,
    fiscal_yr_end = Fiscal_Year_End_New__c
        )]# %>% 
    # .[!(sf_name %in% c(
    #   'Intermountain Power Agency',
    #   'test city 2',
    #   'Utah Associated Municipal Power Systems',
    #   'Utah Municipal Power Agency',
    #   "My Account",
    #   "salesforce.com",
    #   "State of Utah"))
    #   ] %>% 
   ####### # .[!(entity_status %in% c("Inactive", "Dissolved"))]# %>% 
    # .[exprev_start_date < today() || is.na(exprev_start_date)] %>% 
    # .[,govt_lvl := fifelse( sf_name %in%
    #       c("State of Utah",
    #         "Utah System of Higher Education - Student Loan Guarantee Program",
    #         "Utah System of Higher Education - Student Loan Purchase Program",
    #         "Utah System of Higher Education - Utah Educational Savings Plan dba my529",
    #         "Utah System of Higher Education - Utah State Board of Regents"),
    #       "Monitored State Agency",
    #       govt_lvl)] #%>% 
    # .[govt_lvl != "State of Utah (agencies/depts/comp units/ etc.)"]
    

tax_holding_entity <- sf_account[,.(tax_holding_county_id = sf_id,
         tax_holding_county= sf_name)]

sf_account <- merge(sf_account, tax_holding_entity, all.x=T, by="tax_holding_county_id")

sf_account <- sf_account[, `:=`(
  street = case_when(
    is.na(ship_street) & !is.na(bill_street) ~ bill_street,
    !is.na(ship_street) &  is.na(bill_street) ~ ship_street,
    !is.na(ship_street) & !is.na(bill_street) ~ ship_street,
    TRUE ~ ""
  ),
  city = case_when(
    is.na(ship_city) & !is.na(bill_city) ~ bill_city,
    !is.na(ship_city) &  is.na(bill_city) ~ ship_city,
    !is.na(ship_city) &  !is.na(bill_city) ~ ship_city,
    TRUE ~ ""
  ),
  state = case_when(
    is.na(ship_state) & !is.na(bill_state) ~ bill_state,
    !is.na(ship_state) & is.na(bill_state) ~ ship_state,
    !is.na(ship_state) & !is.na(bill_state) ~ ship_state,
    TRUE ~ ""
  ),
  postal_code =  case_when(
    is.na(ship_pc) & !is.na(bill_pc) ~ bill_pc,
    !is.na(ship_pc) & is.na(bill_pc) ~ ship_pc,
    !is.na(ship_pc) &  !is.na(bill_pc) ~ ship_pc,
    TRUE ~ ""
  )
)] %>%
.[,c("ship_street",
     "ship_city",
     "ship_state",
     "ship_pc",
     "bill_street",
     "bill_city",
     "bill_state",
     "bill_pc"):=NULL] %>%
  .[, postal_code:=postal_code %>% stri_extract_first_regex("\\d{5}")]

```


### Query the contact object
get the chief administrator officers information.
```{r}
temp_soql <- paste0(" 
          SELECT 
            Name,
            AccountId,
            Role__c,
            Email,
            Is_Primary__c
          FROM Contact
          WHERE (Role__c IN ('CAO','CFO') OR Is_Primary__c=TRUE) AND IsDeleted = FALSE AND IsDeactivated__c =FALSE
                    ")

sf_cao <- sf_query(temp_soql)%>%
  as.data.table() %>% 
  .[,.( 
        sf_id = AccountId,
        name = Name, 
        email=Email,
        role = Role__c,
        is_primary = Is_Primary__c
        )
    ] 
```



```{r}
contact_info <- merge(sf_account, sf_cao, all.x=T, by="sf_id")
```


# Tran Report
```{r}
temp_soql <- paste0("
                    SELECT CreatedDate
                    FROM Transparency_Reporting__c
                    ORDER BY CreatedDate DESC
                    LIMIT 500")
max_date <- sf_query(temp_soql) %>% as.data.table() %>% 
  .[,created_date := CreatedDate %>% as.Date("%Y/%m/%d")] %>% 
  .[,.(freq=.N),by=created_date] %>% 
  .[freq==max(freq)] %>% 
  .[["created_date"]]
  
print("done max_date")

temp_soql <- paste0("
                    SELECT 
                      Transparency_Reporting__c.Account__c,
                      Transparency_Reporting__c.Expenditure_Problem__c,
                      Transparency_Reporting__c.Revenue_Problem__c,
                      Transparency_Reporting__c.Wage_Problem__c,
                      Transparency_Reporting__c.CreatedDate
                    FROM Transparency_Reporting__c
                    WHERE DAY_ONLY(Transparency_Reporting__c.CreatedDate) = ",max_date)

sf_trans_report <- sf_query(temp_soql)%>%
  as.data.table() %>% 
  .[,.( sf_id        = Account__c,
        miss_exp     = Expenditure_Problem__c,
        miss_rev     = Revenue_Problem__c,
        miss_pay     = Wage_Problem__c)]


# report year ------------------------------------------------------------------

temp_soql <- paste0(" SELECT  Name,  Id  FROM Report_Year__c
                      WHERE IsDeleted = FALSE  AND (Delinquent_Reports__c > 0  OR Delinquent_Budget__c > 0 OR Action_Required_Reports__c > 0)")
# temp_soql <- paste0(" SELECT  Name,  Id  FROM Report_Year__c
#                       WHERE IsDeleted = FALSE ")
sf_report_year <- sf_query(temp_soql)%>% as.data.table() %>% .[,.(report_year=Name,
                                                                  report_status=Id)]

```


# LG REPORT
```{r}
temp_soql <- paste0(" SELECT Account__c,
                            Delinquent__c,
                            Report_Type__c,
                            Status__c,
                            IsDeleted,
                            Report_Status__c
                      FROM Reports__c
                      WHERE Status__c IN ('Action Required', 'Delinquent') OR Delinquent__c = TRUE
                    ")
sf_lg_report <- sf_query(temp_soql)%>% as.data.table() %>% 
  .[,.(sf_id = Account__c,
       report_type = Report_Type__c,
       status = Status__c,
       report_status= Report_Status__c
    
  )] %>% 
  .[,missing_report:=paste0(report_type," (",status,")")] %>% 
  .[,.(sf_id = sf_id,
       missing_report=missing_report,
       report_status=report_status)] 

sf_lg_report <- sf_report_year[sf_lg_report, on="report_status"] %>% 
  .[,.( 
    sf_id=sf_id,
    missing_report = paste0(report_year, " ", missing_report )
  )]

sf_lg_report <-  sf_lg_report[,.(miss_lg = missing_report %>% paste0(collapse=", ")),
                              by="sf_id"] %>% 
  .[,`:=`(miss_lg =fifelse(stri_detect_regex(miss_lg, "^NA (?=.+)" ),
                           stri_replace_first_regex(miss_lg, "^NA (?=.+)","" ),
                           miss_lg
                           )
          )
    ]
```

# DANDI
```{r}
temp_soql <- paste0(" 
          SELECT 
            Name,
            Enity_Name__c,
            Status__c,
            Year__c
            
            
          FROM Deposit_Investment_Report__c
          
          WHERE Status__c = 'Not Submitted'
                    ")

sf_dandi <- sf_query(temp_soql)%>%
  as.data.table() %>% 
  .[,.( sf_id = Enity_Name__c,
        miss_dandi = Name,
        status = Status__c#,
        #year = Year__c
  )
  ] %>%  #%>% 
  .[,`:=`(
    di_year = miss_dandi %>% stri_extract_first_regex("\\d{4}$") %>% as.numeric(),
    di_month_name = miss_dandi %>% stri_extract_first_regex("(?<=D&I )([[:alpha:]])+(?= \\d{4}$)")
  )] %>%
  .[,
    di_month := match(di_month_name,month.name)] %>% 
  .[di_year < 2021] %>% 
  .[,.(miss_dandi = paste0(miss_dandi, " (",status,")" ),
       sf_id)] %>% 
  .[,.(miss_dandi = paste0(miss_dandi, collapse=",")),by=c("sf_id")]
```




```{r}
full_compliance_object <- merge(sf_trans_report, sf_account, by="sf_id", all.x=F, all.y=T) %>% 
  
  merge(sf_lg_report, by="sf_id", all.x=T, all.y=F) %>% 

# full_compliance_object <-  sf_lg_report[full1, on="sf_id"] %>% 
  merge(sf_dandi, by="sf_id", all.x=T, all.y=F) %>% 
  .[,`:=`(miss_rev = miss_rev %>% map_chr(fix_exprev_str_v2),
           miss_exp = miss_exp %>% map_chr(fix_exprev_str_v2),
           # missing_reports = fifelse(missing_reports=="",
           #                           "NA",
           #                           missing_reports),
           miss_lg = miss_lg %>%
             map_chr(~fifelse(is.null(.),
                              "NA",
                              fifelse(is.na(.),
                                      "NA",
                                      fifelse(.=="",
                                              "NA",
                                              .
                                      )
                              )
             )
             ),
          miss_dandi = miss_dandi %>%
            map_chr(~fifelse(is.null(.),
                             "NA",
                             fifelse(is.na(.),
                                     "NA",
                                     fifelse(.=="",
                                             "NA",
                                             .
                                     )
                             )
            )
            ),
           miss_pay = miss_pay %>%
             map_chr(~fifelse(is.null(.),
                              "NA",
                              fifelse(is.na(.),
                                      "NA",
                                      fifelse(.=="",
                                              "NA",
                                              .)
                              )
             )
             )
  )]
```





```{r}
full_compliance_object <- full_compliance_object[,`:=`(file_name = sf_name %>% map_chr(create_email_pdf_file_name))] %>%
  .[miss_rev!="NA" | miss_exp!="NA" | miss_pay!="NA" | miss_lg!="NA" | miss_dandi!="NA"]
```


```{r}
email_building_start <- Sys.time()
pwalk(list(miss_exp_p=full_compliance_object$miss_exp,
              miss_rev_p=full_compliance_object$miss_rev,
              miss_pay_p =full_compliance_object$miss_pay,
              miss_lg_p = full_compliance_object$miss_lg,
              miss_dandi_p = full_compliance_object$miss_dandi,
              entity_name_p = full_compliance_object$sf_name,
              file_dir_p ="D:/rprojects/compliance-report/mm/email",
              file_name_p = full_compliance_object$file_name,
              report_type_p="60day_notice"),
      create_email_pdf)
email_building_end <- Sys.time()
```


# Now Upload to google drive

```{r}
library(googledrive)
drive_auth()
```

```{r}

```


```{r}

gd_folder <- Sys.Date() %>% stri_replace_all_regex("-","_") %>% paste0("mm_",.) %>%  drive_mkdir()
```

```{r}
filename_id_dict <- data.table(file_name = character(), id=character())

for (file_name_t in full_compliance_object$file_name){
  
  print(file_name_t)
  
  temp_file_path <-  paste0("D:/rprojects/compliance-report/mm/email/",file_name_t)
  
  drive_upload(media=temp_file_path,
               path=gd_folder,
               overwrite=T)
  
  temp_drive_object <-  drive_get(paste0("mm_test_2021_06_22","/",file_name_t))
  
  temp_dt <- data.table(file_name = file_name_t, id = temp_drive_object$id )
  
  filename_id_dict <- filename_id_dict %>% rbind(temp_dt)
  # print(temp_drive_object)
}
```

```{r}
mm_final <- full_compliance_object %>%
  merge(contact_info, all.x=T, all.y=F, by="sf_id")%>%
  merge(filename_id_dict,all.x=T, all.y=F, by="file_name") %>% 
  .[,.(
    sf_id,
    sf_name = sf_name.x,
    govt_lvl = govt_lvl.x,
    entity_status = entity_status.x,
    name,
    email, 
    role,
    is_primary,
    
    miss_lg= ifelse(miss_lg=="NA", NA, miss_lg) ,
    miss_dandi = ifelse(miss_dandi=="NA", NA, miss_dandi),
    miss_exp = ifelse(miss_exp=="NA", NA, miss_exp),
    miss_rev = ifelse(miss_rev=="NA", NA, miss_rev),
    miss_pay = ifelse(miss_pay=="NA", NA, miss_pay),
    attachment1_google_id = id
    
  )] %>% 
  .[!(govt_lvl %in% c("CPA Firm",
                     "Non Profits"))]
```

```{r}
mm_final %>% fwrite(paste0(Sys.Date(),"-mm_email.csv"))
```


